---
title: "mesh explorations"
author: "Christopher Perez"
date: "2026-04-15"
output: html_document
---
```{r}
library(rgl)
library(plotly)
library(SurfaceReconstruction)
```

```{r}
random_sphere <- function(n) {
  u <- runif(n, -1, 1)
  phi <- runif(n, 0, 2*pi)
  theta <- acos(u)     # correct relation
  x <- sin(theta)*cos(phi)
  y <- sin(theta)*sin(phi)
  z <- cos(theta)
  cbind(x,y,z)
}
unifmoon2d3D <- function(N, oversample = 5, bend = pi,
                         radius = 1, bend_radius = 1.2, noise=0) {
  
  # 1. oversample sphere uniformly
  S <- random_sphere(N * oversample)
  
  x <- radius * S[,1]
  y <- radius * S[,2]
  z <- radius * S[,3]
  
  # 2. bend map
  new_x <- cos(bend * x / (2*radius)) * (bend_radius * radius + y)
  new_y <- sin(bend * x / (2*radius)) * (bend_radius * radius + y)
  new_z <- z
  
  pts <- cbind(new_x, new_y, new_z)
  
  # 3. Rejection thinning for uniform coverage
  # compute kernel density to approximate sampling density
  library(FNN)
  k <- 10
  d <- get.knn(pts, k)$nn.dist[,k]       # k-th NN distance
  w <- d^3                               # local volume ~ r^3
  prob <- w / max(w)
  
  keep <- sample(seq_len(nrow(pts)), N, prob=prob)
  
  list(X = pts[keep,] + rnorm(3*N, sd=noise),
       t = S[keep,])
}

plot_data_3D <- function(X, col=NULL){
  if(!is.null(col)){
    
    g <-plot_ly() %>%
      # Scatter points trace
      add_markers(x = X[, 1],y = X[, 2], z = X[, 3],
                  type = "scatter3d",
                  mode = "markers",
                  marker = list(size = 2,opacity=0.7, color=col[,3]),
                  name = "Data points")
  }
  else{
    g <- plot_ly() %>%
      # Scatter points trace
      add_markers(x = X[, 1],y = X[, 2], z = X[, 3],
                  type = "scatter3d",
                  mode = "markers",
                  marker = list(size = 2,opacity=0.7),
                  name = "Data points"
      )
  }
 
  g
}
```

```{r}
set.seed(1)
N <- 600
X <- unifmoon2d3D(N, bend=1.5*pi, bend_radius = 2)


plot_data_3D(X$X)
```

```{r}
library(TDA)
#library(devtools)
library(rgl)
# remotes::install_github("stla/SurfaceReconstruction")
library(SurfaceReconstruction)

set.seed(1)
N <- 1000
X <- unifmoon2d3D(N, bend=1.5*pi, bend_radius = 2, noise=0.05)

data <- X$X
plot_data_3D(data)

Xlim <- c(min(data[,1]), max(data[,1]))
Ylim <- c(min(data[,2]), max(data[,2]))
Zlim <- c(min(data[,3]), max(data[,3]))
lim <- cbind(Xlim, Ylim,Zlim)


#fit <- bootstrapDiagram(X$X, FUN = distFct, lim  =lim, by=0.05)

fit <- gridDiag(X = data, FUN=distFct, lim=lim, by=0.1)

png("mytda.png",width=1200,height=1200,res=200)
plot(fit$diagram,asp=1);legend(1.5,0.75, c("0", "1", "2"), col=c(1,2,4), pch=c(20,2, 5), cex=0.9, pt.lwd=2)


mesh <- PoissonReconstruction(X$X)
clear3d()
open3d(windowRect=c(0,0,1000,1000), antialias=4)
shade3d(mesh, color="pink")
wire3d(mesh, color="black")
rglwidget()
#rgl.snapshot
```


```{r}
#chatgpt

library(png)
library(grid)

img1 <- readPNG("mytda.png")
img2 <- readPNG("myhole.png")

png("combined.png", width = 2200, height = 1200)

grid.newpage()
pushViewport(viewport(layout = grid.layout(1, 2)))

grid.raster(img1, vp = viewport(layout.pos.row = 1, layout.pos.col = 1))
grid.raster(img2, vp = viewport(layout.pos.row = 1, layout.pos.col = 2))

dev.off()
```


Noisy

```{r}

N <- 1000
X <- unifmoon2d3D(N, bend=1.5*pi, bend_radius = 2, noise=1)

data <- X$X
plot_data_3D(data)

mesh <- PoissonReconstruction(X$X)
clear3d()
open3d(windowRect=c(0,0,1000,1000), antialias=4)
shade3d(mesh, color="pink")
wire3d(mesh, color="black")
rglwidget()
```

